In [1]:
import pandas as pd

In [2]:
df_train = pd.read_parquet("../../data/churn-prediction-25-26/train.parquet")

In [28]:
df = df_train.copy()

In [29]:
df["last_time"] = df.groupby(["userId"])["time"].transform("max")
df["last_item"] = df.groupby(["userId", "sessionId"])["itemInSession"].transform("max")

In [43]:
temp = df[(df["time"] == df["last_time"]) & \
          (df["itemInSession"] == df["last_item"])][["userId", "level"]]

In [44]:
temp

           userId level
6662491   1749042  paid
11181150  1563081  paid
16470785  1697168  paid
9995603   1222580  paid
16201413  1714398  paid
...           ...   ...
25649305  1494594  free
25661569  1036641  free
25661409  1110980  paid
25661132  1594272  paid
25661583  1152881  paid

[19140 rows x 2 columns]

In [45]:
temp["level"] = temp["level"] == "paid"
temp["level"] = temp["level"].astype(int)

In [46]:
temp

           userId  level
6662491   1749042      1
11181150  1563081      1
16470785  1697168      1
9995603   1222580      1
16201413  1714398      1
...           ...    ...
25649305  1494594      0
25661569  1036641      0
25661409  1110980      1
25661132  1594272      1
25661583  1152881      1

[19140 rows x 2 columns]